language: python
python:
  - "2.7"	
  - "3.4"
cache: pip
install:
  - pip install -r test_requirements.txt
  - pip install -e .
  - travis_wait 60 mvn install
script: 
  - pytest
branches:
  only:
    - master
